/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "myfinger.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

myfinger_out *
myfinger_1(myfinger_in *argp, CLIENT *clnt)
{
	static myfinger_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MYFINGER,
		(xdrproc_t) xdr_myfinger_in, (caddr_t) argp,
		(xdrproc_t) xdr_myfinger_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
