/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "myfinger.h"

bool_t
xdr_myfinger_in (XDR *xdrs, myfinger_in *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->user_name, 4096,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_myfinger_out (XDR *xdrs, myfinger_out *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->output, 4096,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
