/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MYFINGER_H_RPCGEN
#define _MYFINGER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct myfinger_in {
	char user_name[4096];
};
typedef struct myfinger_in myfinger_in;

struct myfinger_out {
	char output[4096];
};
typedef struct myfinger_out myfinger_out;

#define MYFINGER_PROGRAM 0x31230000
#define MYFINGER_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define MYFINGER 1
extern  myfinger_out * myfinger_1(myfinger_in *, CLIENT *);
extern  myfinger_out * myfinger_1_svc(myfinger_in *, struct svc_req *);
extern int myfinger_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MYFINGER 1
extern  myfinger_out * myfinger_1();
extern  myfinger_out * myfinger_1_svc();
extern int myfinger_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_myfinger_in (XDR *, myfinger_in*);
extern  bool_t xdr_myfinger_out (XDR *, myfinger_out*);

#else /* K&R C */
extern bool_t xdr_myfinger_in ();
extern bool_t xdr_myfinger_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MYFINGER_H_RPCGEN */
